### ISSUE TITLE
service is not restarted 

### ISSUE THREAD

**Issue by myunusov** [myunusov/maxur-mserv#28]
java.lang.IllegalStateException: ServiceLocatorImpl(locator-1,0,989892772) has been shut down
	at org.jvnet.hk2.internal.ServiceLocatorImpl.checkState(ServiceLocatorImpl.java:2371)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:743)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:737)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:707)
	at org.maxur.mserv.core.service.hk2.LocatorHK2Impl.service(LocatorHK2Impl.kt:27)
	at org.maxur.mserv.core.domain.BaseService$State.call(BaseService.kt:99)
	at org.maxur.mserv.core.domain.BaseService$State.launch(BaseService.kt:85)
	at org.maxur.mserv.core.domain.BaseService$State$STARTED.restart(BaseService.kt:57)
	at org.maxur.mserv.core.MicroService$deferredRestart$1.invoke(MicroService.kt:36)
	at org.maxur.mserv.core.MicroService$deferredRestart$1.invoke(MicroService.kt:14)
	at org.maxur.mserv.core.MicroService$postpone$1.run(MicroService.kt:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by myunusov** [comment]
private void checkState() {
        if (ServiceLocatorState.SHUTDOWN.equals(state)) throw new IllegalStateException(this + " has been shut down");
    }
